import './index.css'
import './index.html'
import './condense_template'

import './custom_elements/action_config'
import './custom_elements/action_group_modal'
import './custom_elements/block_list'
import './custom_elements/bulma_dropdown'
import './custom_elements/config_manager'
import './custom_elements/configuration'
import './custom_elements/directory_manager'
import './custom_elements/search_engine_editor_modal'
import './custom_elements/search_engine_manager'
import './custom_elements/search_engine_provider'
import './custom_elements/settings'
import './custom_elements/tabs'
